# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Apply Secguro

on:
  push:
    branches-ignore:
      - 'master'
      - 'gh-pages'

jobs:

  build:
    name: Build and Apply Secguro Job
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: default_environment
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.7'

    - name: Set up Linter
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0

    - name: Check for Linting Violations
      run: make lint

    - name: Build
      run: make

    - name: Test
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      # Disable dependencycheck to prevent excessive load on NVD.
      run: build/secguro scan --disabled-detectors dependencycheck
